dist: trusty
sudo: false
notifications:
  email: false
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
if: tag IS blank

jobs:
  include:
    - stage: deploy to cf
      before_deploy:
        - echo "Deploying $RELEASE_TAG to Cloud Foundry"
      before_script:
        - chmod 777 scripts/migrate-databases.sh
        - scripts/migrate-databases.sh pal-tracker .
